spring:
  application:
    name: team-profile
  profiles:
    active: local
  cloud:
    aws:
      region:
        static: ap-northeast-2
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  team-name: ${my-name}